import { TutorContent, TutorLine } from './lesson-tutor-content.types';

const LESSON_3_WORDS: TutorContent['words'] = [
  { sourceOrder: 1, word: '九月', pinyin: 'jiǔyuè', partOfSpeech: 'n', definition: 'September', isProperNoun: false },
  { sourceOrder: 2, word: '月', pinyin: 'yuè', partOfSpeech: 'n', definition: 'month', isProperNoun: false },
  { sourceOrder: 3, word: '十二', pinyin: "shí'èr", partOfSpeech: 'nu', definition: 'twelve', isProperNoun: false },
  { sourceOrder: 4, word: '号', pinyin: 'hào', partOfSpeech: 'm', definition: 'day of the month; number in a series', isProperNoun: false },
  { sourceOrder: 5, word: '星期', pinyin: 'xīngqī', partOfSpeech: 'n', definition: 'week', isProperNoun: false },
  { sourceOrder: 6, word: '星期四', pinyin: 'xīngqīsì', partOfSpeech: 'n', definition: 'Thursday', isProperNoun: false },
  { sourceOrder: 7, word: '天', pinyin: 'tiān', partOfSpeech: 'n', definition: 'day', isProperNoun: false },
  { sourceOrder: 8, word: '生日', pinyin: 'shēngrì', partOfSpeech: 'n', definition: 'birthday', isProperNoun: false },
  { sourceOrder: 9, word: '今年', pinyin: 'jīnnián', partOfSpeech: 't', definition: 'this year', isProperNoun: false },
  { sourceOrder: 10, word: '多', pinyin: 'duō', partOfSpeech: 'adv', definition: 'how many/much; to what extent; many', isProperNoun: false },
  { sourceOrder: 11, word: '大', pinyin: 'dà', partOfSpeech: 'adj', definition: 'big; old', isProperNoun: false },
  { sourceOrder: 12, word: '十八', pinyin: 'shíbā', partOfSpeech: 'nu', definition: 'eighteen', isProperNoun: false },
  { sourceOrder: 13, word: '岁', pinyin: 'suì', partOfSpeech: 'n', definition: 'year of age', isProperNoun: false },
  { sourceOrder: 14, word: '吃', pinyin: 'chī', partOfSpeech: 'v', definition: 'to eat', isProperNoun: false },
  { sourceOrder: 15, word: '饭', pinyin: 'fàn', partOfSpeech: 'n', definition: 'meal; cooked rice', isProperNoun: false },
  { sourceOrder: 16, word: '怎么样', pinyin: 'zěnmeyàng', partOfSpeech: 'qpr', definition: 'How is that? How does that sound?', isProperNoun: false },
  { sourceOrder: 17, word: '太…了', pinyin: 'tài...le', partOfSpeech: 'expr', definition: 'too; extremely', isProperNoun: false },
  { sourceOrder: 18, word: '谢谢', pinyin: 'xièxie', partOfSpeech: 'v', definition: 'to thank', isProperNoun: false },
  { sourceOrder: 19, word: '喜欢', pinyin: 'xǐhuan', partOfSpeech: 'v', definition: 'to like', isProperNoun: false },
  { sourceOrder: 20, word: '菜', pinyin: 'cài', partOfSpeech: 'n', definition: 'dishes; cuisine', isProperNoun: false },
  { sourceOrder: 21, word: '还是', pinyin: 'háishi', partOfSpeech: 'conj', definition: 'or', isProperNoun: false },
  { sourceOrder: 22, word: '可是', pinyin: 'kěshì', partOfSpeech: 'conj', definition: 'but', isProperNoun: false },
  { sourceOrder: 23, word: '我们', pinyin: 'wǒmen', partOfSpeech: 'pr', definition: 'we', isProperNoun: false },
  { sourceOrder: 24, word: '点', pinyin: 'diǎn', partOfSpeech: 'm', definition: "o'clock", isProperNoun: false },
  { sourceOrder: 25, word: '半', pinyin: 'bàn', partOfSpeech: 'nu', definition: 'half; half an hour', isProperNoun: false },
  { sourceOrder: 26, word: '晚上', pinyin: 'wǎnshang', partOfSpeech: 't/n', definition: 'evening; night', isProperNoun: false },
  { sourceOrder: 27, word: '见', pinyin: 'jiàn', partOfSpeech: 'v', definition: 'to see', isProperNoun: false },
  { sourceOrder: 28, word: '再见', pinyin: 'zàijiàn', partOfSpeech: 'v', definition: 'goodbye; see you again', isProperNoun: false },
  { sourceOrder: 29, word: '英国', pinyin: 'Yīngguó', partOfSpeech: 'pn', definition: 'Britain; England', isProperNoun: true },
  { sourceOrder: 30, word: '现在', pinyin: 'xiànzài', partOfSpeech: 't', definition: 'now', isProperNoun: false },
  { sourceOrder: 31, word: '刻', pinyin: 'kè', partOfSpeech: 'm', definition: 'quarter of an hour', isProperNoun: false },
  { sourceOrder: 32, word: '事儿', pinyin: 'shìr', partOfSpeech: 'n', definition: 'matter; affair; event', isProperNoun: false },
  { sourceOrder: 33, word: '今天', pinyin: 'jīntiān', partOfSpeech: 't', definition: 'today', isProperNoun: false },
  { sourceOrder: 34, word: '很', pinyin: 'hěn', partOfSpeech: 'adv', definition: 'very', isProperNoun: false },
  { sourceOrder: 35, word: '忙', pinyin: 'máng', partOfSpeech: 'adj', definition: 'busy', isProperNoun: false },
  { sourceOrder: 36, word: '明天', pinyin: 'míngtiān', partOfSpeech: 't', definition: 'tomorrow', isProperNoun: false },
  { sourceOrder: 37, word: '晚饭', pinyin: 'wǎnfàn', partOfSpeech: 'n', definition: 'dinner; supper', isProperNoun: false },
  { sourceOrder: 38, word: '为什么', pinyin: 'wèishénme', partOfSpeech: 'qpr', definition: 'why', isProperNoun: false },
  { sourceOrder: 39, word: '因为', pinyin: 'yīnwèi', partOfSpeech: 'conj', definition: 'because', isProperNoun: false },
  { sourceOrder: 40, word: '还', pinyin: 'hái', partOfSpeech: 'adv', definition: 'also; too; as well', isProperNoun: false },
  { sourceOrder: 41, word: '同学', pinyin: 'tóngxué', partOfSpeech: 'n', definition: 'classmate', isProperNoun: false },
  { sourceOrder: 42, word: '认识', pinyin: 'rènshi', partOfSpeech: 'v', definition: 'to be acquainted with; to recognize', isProperNoun: false },
  { sourceOrder: 43, word: '朋友', pinyin: 'péngyou', partOfSpeech: 'n', definition: 'friend', isProperNoun: false },
];

const LESSON_3_DIALOGUES: TutorLine[][] = [
  [
    { id: -301, chinese: '白英爱，九月十二号是星期几？', pinyin: "Bái Yīng'ài, jiǔyuè shí'èr hào shì xīngqījǐ?", english: "Bai Ying'ai, what day of the week is September 12?", dialogueNumber: 1, sequenceOrder: 1, keyVocab: ['九月', '十二', '号', '星期'] },
    { id: -302, chinese: '是星期四。', pinyin: 'Shì xīngqīsì.', english: "It's Thursday.", dialogueNumber: 1, sequenceOrder: 2, keyVocab: ['星期四'] },
    { id: -303, chinese: '那天是我的生日。', pinyin: 'Nà tiān shì wǒ de shēngrì.', english: 'That day is my birthday.', dialogueNumber: 1, sequenceOrder: 3, keyVocab: ['天', '生日'] },
    { id: -304, chinese: '是吗？你今年多大？', pinyin: 'Shì ma? Nǐ jīnnián duō dà?', english: 'Really? How old are you this year?', dialogueNumber: 1, sequenceOrder: 4, keyVocab: ['今年', '多', '大'] },
    { id: -305, chinese: '十八岁。', pinyin: 'Shíbā suì.', english: 'Eighteen years old.', dialogueNumber: 1, sequenceOrder: 5, keyVocab: ['十八', '岁'] },
    { id: -306, chinese: '我星期四请你吃饭，怎么样？', pinyin: 'Wǒ xīngqīsì qǐng nǐ chī fàn, zěnmeyàng?', english: "I'll invite you to dinner on Thursday. How does that sound?", dialogueNumber: 1, sequenceOrder: 6, keyVocab: ['星期四', '吃', '饭', '怎么样'] },
    { id: -307, chinese: '太好了。谢谢，谢谢。', pinyin: 'Tài hǎo le. Xièxie, xièxie.', english: 'Great. Thank you, thank you.', dialogueNumber: 1, sequenceOrder: 7, keyVocab: ['太…了', '谢谢'] },
    { id: -308, chinese: '你喜欢吃中国菜还是美国菜？', pinyin: 'Nǐ xǐhuan chī Zhōngguó cài háishi Měiguó cài?', english: 'Do you like to eat Chinese food or American food?', dialogueNumber: 1, sequenceOrder: 8, keyVocab: ['喜欢', '菜', '还是'] },
    { id: -309, chinese: '我是英国人，可是我喜欢吃中国菜。', pinyin: 'Wǒ shì Yīngguó rén, kěshì wǒ xǐhuan chī Zhōngguó cài.', english: "I'm British, but I like to eat Chinese food.", dialogueNumber: 1, sequenceOrder: 9, keyVocab: ['英国', '可是', '喜欢'] },
    { id: -310, chinese: '好，我们吃中国菜。', pinyin: 'Hǎo, wǒmen chī Zhōngguó cài.', english: "OK, we'll eat Chinese food.", dialogueNumber: 1, sequenceOrder: 10, keyVocab: ['我们', '吃', '菜'] },
    { id: -311, chinese: '星期四几点？', pinyin: 'Xīngqīsì jǐ diǎn?', english: 'What time on Thursday?', dialogueNumber: 1, sequenceOrder: 11, keyVocab: ['星期四', '点'] },
    { id: -312, chinese: '七点半怎么样？', pinyin: 'Qī diǎn bàn zěnmeyàng?', english: 'How about 7:30?', dialogueNumber: 1, sequenceOrder: 12, keyVocab: ['点', '半', '怎么样'] },
    { id: -313, chinese: '好，星期四晚上见。', pinyin: 'Hǎo, xīngqīsì wǎnshang jiàn.', english: 'OK, see you Thursday evening.', dialogueNumber: 1, sequenceOrder: 13, keyVocab: ['晚上', '见'] },
    { id: -314, chinese: '再见！', pinyin: 'Zàijiàn!', english: 'Goodbye!', dialogueNumber: 1, sequenceOrder: 14, keyVocab: ['再见'] },
  ],
  [
    { id: -401, chinese: '白英爱，现在几点？', pinyin: "Bái Yīng'ài, xiànzài jǐ diǎn?", english: "Bai Ying'ai, what time is it now?", dialogueNumber: 2, sequenceOrder: 1, keyVocab: ['现在', '点'] },
    { id: -402, chinese: '五点三刻。', pinyin: 'Wǔ diǎn sān kè.', english: 'Five forty-five.', dialogueNumber: 2, sequenceOrder: 2, keyVocab: ['点', '刻'] },
    { id: -403, chinese: '我六点一刻有事儿。', pinyin: 'Wǒ liù diǎn yí kè yǒu shìr.', english: 'I have something to do at six fifteen.', dialogueNumber: 2, sequenceOrder: 3, keyVocab: ['点', '刻', '事儿'] },
    { id: -404, chinese: '你今天很忙，明天忙不忙？', pinyin: 'Nǐ jīntiān hěn máng, míngtiān máng bu máng?', english: 'You are busy today. Are you busy tomorrow?', dialogueNumber: 2, sequenceOrder: 4, keyVocab: ['今天', '很', '忙', '明天'] },
    { id: -405, chinese: '我今天很忙，可是明天不忙。有事儿吗？', pinyin: 'Wǒ jīntiān hěn máng, kěshì míngtiān bù máng. Yǒu shìr ma?', english: "I'm busy today, but not busy tomorrow. Is something up?", dialogueNumber: 2, sequenceOrder: 5, keyVocab: ['今天', '忙', '可是', '明天', '事儿'] },
    { id: -406, chinese: '明天我请你吃晚饭，怎么样？', pinyin: 'Míngtian wǒ qǐng nǐ chī wǎnfàn, zěnmeyàng?', english: "Tomorrow I'll invite you to dinner. How does that sound?", dialogueNumber: 2, sequenceOrder: 6, keyVocab: ['明天', '晚饭', '怎么样'] },
    { id: -407, chinese: '你为什么请我吃饭？', pinyin: 'Nǐ wèishénme qǐng wǒ chī fàn?', english: 'Why are you inviting me to dinner?', dialogueNumber: 2, sequenceOrder: 7, keyVocab: ['为什么', '吃饭'] },
    { id: -408, chinese: '因为明天是高文中的生日。', pinyin: 'Yīnwei míngtiān shì Gāo Wénzhōng de shēngrì.', english: "Because tomorrow is Gao Wenzhong's birthday.", dialogueNumber: 2, sequenceOrder: 8, keyVocab: ['因为', '明天', '生日'] },
    { id: -409, chinese: '是吗？好。还请谁？', pinyin: 'Shì ma? Hǎo. Hái qǐng shéi?', english: 'Really? OK. Who else are you inviting?', dialogueNumber: 2, sequenceOrder: 9, keyVocab: ['还', '谁'] },
    { id: -410, chinese: '还请我的同学李友。', pinyin: 'Hái qǐng wǒ de tóngxué Lǐ Yǒu.', english: "I'm also inviting my classmate Li You.", dialogueNumber: 2, sequenceOrder: 10, keyVocab: ['还', '同学'] },
    { id: -411, chinese: '那太好了，我认识李友，她也是我的朋友。明天几点？', pinyin: 'Nà tài hǎo le. Wǒ rènshi Lǐ Yǒu, tā yě shì wǒ de péngyou. Míngtiān jǐ diǎn?', english: "That's great. I know Li You; she is also my friend. What time tomorrow?", dialogueNumber: 2, sequenceOrder: 11, keyVocab: ['太…了', '认识', '朋友', '明天'] },
    { id: -412, chinese: '明天晚上七点半。', pinyin: 'Míngtiān wǎnshang qī diǎn bàn.', english: 'Tomorrow evening at 7:30.', dialogueNumber: 2, sequenceOrder: 12, keyVocab: ['明天', '晚上', '点', '半'] },
    { id: -413, chinese: '好，明天七点半见。', pinyin: 'Hǎo, míngtiān qī diǎn bàn jiàn.', english: 'OK, see you tomorrow at 7:30.', dialogueNumber: 2, sequenceOrder: 13, keyVocab: ['明天', '点', '半', '见'] },
  ],
];


export const LESSON_3_TUTOR_CONTENT: TutorContent = {
    lessonNumber: 3,
    title: 'Dates and Time',
    chineseTitle: '时间',
    pinyinTitle: 'Dì sān kè Shíjiān',
    heroCopy: 'Practice dates, birthdays, invitations, and dinner plans from the Lesson 3 dialogues.',
    sourceNote: 'Source: textbook.pdf Lesson 3',
    detailRoute: '/lessons/3',
    dialogueTitle: 'Dialogue I: Birthday Dinner Invitation',
    dialogueGuide: 'Listen for the date, birthday, food choice, and meeting time before revealing support.',
    vocabNote: 'Curated from the textbook extract and normalized for Lesson 3 order.',
    words: LESSON_3_WORDS,
    dialogues: LESSON_3_DIALOGUES,
    patterns: [
      { title: 'Dates', example: '九月十二号是星期几？', explanation: 'Chinese dates move from larger units to smaller units.' },
      { title: 'Age', example: '你今年多大？ 十八岁。', explanation: 'Use 多大 to ask age and 岁 to state age.' },
      { title: '还是', example: '中国菜还是美国菜？', explanation: 'Use 还是 to ask an alternative question.' },
      { title: 'A-not-A', example: '明天忙不忙？', explanation: 'Repeat the adjective or verb in affirmative and negative form to ask yes/no.' },
      { title: '还', example: '还请谁？', explanation: 'Use 还 when adding someone or something else.' },
    ],
    drills: [
      { id: 'date-order', prompt: 'Which phrase asks what weekday September 12 is?', choices: ['九月十二号是星期几？', '九月十二号几点？', '九月十二号几岁？'], answer: '九月十二号是星期几？', selected: '', explanation: '星期几 asks which day of the week.' },
      { id: 'age', prompt: 'Choose the natural age answer for 你今年多大？', choices: ['十八岁。', '十八年。', '十八点。'], answer: '十八岁。', selected: '', explanation: '岁 marks years of age.' },
      { id: 'haishi', prompt: 'Which word makes a choice question?', choices: ['还是', '可是', '因为'], answer: '还是', selected: '', explanation: '还是 links alternatives in a question.' },
      { id: 'busy', prompt: 'Which is the A-not-A question?', choices: ['忙不忙？', '很忙。', '不明天。'], answer: '忙不忙？', selected: '', explanation: '忙不忙 repeats the adjective in affirmative and negative form.' },
    ],
    personalPractice: {
      title: 'My Date Builder',
      description: 'Create personal Lesson 3 sentences about birthday, age, food, and dinner time.',
      fields: [
        { key: 'firstNumber', label: 'Age', inputType: 'number', min: 1, max: 120 },
        { key: 'firstText', label: 'Birthday date', inputType: 'text' },
        { key: 'secondText', label: 'Dinner time', inputType: 'text' },
      ],
      selectionHeading: 'Food choices',
      generatedLabel: 'Generated date and invitation lines',
      storageKey: 'lessonTutor.personalProfile.v1.lesson3',
      defaultProfile: {
        firstNumber: 18,
        secondNumber: 0,
        firstText: '九月十二号',
        secondText: '晚上七点半',
        selections: [
          { key: 'chineseFood', label: 'Chinese food', chinese: '中国菜', selected: true, detailText: '' },
          { key: 'americanFood', label: 'American food', chinese: '美国菜', selected: false, detailText: '' },
          { key: 'dinner', label: 'Dinner', chinese: '晚饭', selected: true, detailText: '' },
        ],
      },
      sentenceTemplates: [
        {
          kind: 'single',
          parts: [
            { kind: 'literal', value: '我今年' },
            { kind: 'profile', key: 'firstNumber' },
            { kind: 'literal', value: '岁。' },
          ],
        },
        {
          kind: 'single',
          parts: [
            { kind: 'literal', value: '我的生日是' },
            { kind: 'profile', key: 'firstText', fallback: '九月十二号' },
            { kind: 'literal', value: '。' },
          ],
        },
        {
          kind: 'single',
          parts: [
            { kind: 'literal', value: '我喜欢吃' },
            { kind: 'selectedValue', chineseIncludes: '菜', field: 'chinese', fallback: '中国菜' },
            { kind: 'literal', value: '。' },
          ],
        },
        {
          kind: 'single',
          parts: [
            { kind: 'literal', value: '我请你吃' },
            { kind: 'selectedValue', key: 'dinner', field: 'chinese', fallback: '饭' },
            { kind: 'literal', value: '，怎么样？' },
          ],
        },
        {
          kind: 'single',
          parts: [
            { kind: 'profile', key: 'secondText', fallback: '晚上七点半' },
            { kind: 'literal', value: '见。' },
          ],
        },
      ],
    },
  };
