import { TutorContent, TutorLine, TutorWord } from './lesson-tutor-content.types';

const LESSON_2_WORDS: Array<Pick<TutorWord, 'word' | 'pinyin' | 'partOfSpeech' | 'definition' | 'isProperNoun' | 'sourceOrder'>> = [
  { sourceOrder: 1, word: '那', pinyin: 'nà', partOfSpeech: 'pr', definition: 'that', isProperNoun: false },
  { sourceOrder: 2, word: '的', pinyin: 'de', partOfSpeech: 'p', definition: 'possessive or descriptive particle', isProperNoun: false },
  { sourceOrder: 3, word: '照片', pinyin: 'zhàopiàn', partOfSpeech: 'n', definition: 'picture; photo', isProperNoun: false },
  { sourceOrder: 4, word: '这', pinyin: 'zhè', partOfSpeech: 'pr', definition: 'this', isProperNoun: false },
  { sourceOrder: 5, word: '爸爸', pinyin: 'bàba', partOfSpeech: 'n', definition: 'father, dad', isProperNoun: false },
  { sourceOrder: 6, word: '妈妈', pinyin: 'māma', partOfSpeech: 'n', definition: 'mother, mom', isProperNoun: false },
  { sourceOrder: 7, word: '个', pinyin: 'gè/ge', partOfSpeech: 'm', definition: 'measure word for many common everyday objects', isProperNoun: false },
  { sourceOrder: 8, word: '女', pinyin: 'nǚ', partOfSpeech: 'adj', definition: 'female', isProperNoun: false },
  { sourceOrder: 9, word: '孩子', pinyin: 'háizi', partOfSpeech: 'n', definition: 'child', isProperNoun: false },
  { sourceOrder: 10, word: '谁', pinyin: 'shéi', partOfSpeech: 'qpr', definition: 'who', isProperNoun: false },
  { sourceOrder: 11, word: '她', pinyin: 'tā', partOfSpeech: 'pr', definition: 'she; her', isProperNoun: false },
  { sourceOrder: 12, word: '姐姐', pinyin: 'jiějie', partOfSpeech: 'n', definition: 'older sister', isProperNoun: false },
  { sourceOrder: 13, word: '男', pinyin: 'nán', partOfSpeech: 'adj', definition: 'male', isProperNoun: false },
  { sourceOrder: 14, word: '弟弟', pinyin: 'dìdi', partOfSpeech: 'n', definition: 'younger brother', isProperNoun: false },
  { sourceOrder: 15, word: '他', pinyin: 'tā', partOfSpeech: 'pr', definition: 'he; him', isProperNoun: false },
  { sourceOrder: 16, word: '大哥', pinyin: 'dàgē', partOfSpeech: 'n', definition: 'eldest brother', isProperNoun: false },
  { sourceOrder: 17, word: '儿子', pinyin: 'érzi', partOfSpeech: 'n', definition: 'son', isProperNoun: false },
  { sourceOrder: 18, word: '有', pinyin: 'yǒu', partOfSpeech: 'v', definition: 'to have; to exist', isProperNoun: false },
  { sourceOrder: 19, word: '女儿', pinyin: "nǚ'ér", partOfSpeech: 'n', definition: 'daughter', isProperNoun: false },
  { sourceOrder: 20, word: '没', pinyin: 'méi', partOfSpeech: 'adv', definition: 'not', isProperNoun: false },
  { sourceOrder: 21, word: '高文中', pinyin: 'Gāo Wénzhōng', partOfSpeech: 'pn', definition: 'personal name', isProperNoun: true },
  { sourceOrder: 22, word: '家', pinyin: 'jiā', partOfSpeech: 'n', definition: 'family; home', isProperNoun: false },
  { sourceOrder: 23, word: '几', pinyin: 'jǐ', partOfSpeech: 'nu', definition: 'how many; some; a few', isProperNoun: false },
  { sourceOrder: 24, word: '口', pinyin: 'kǒu', partOfSpeech: 'm', definition: 'measure word for number of family members', isProperNoun: false },
  { sourceOrder: 25, word: '哥哥', pinyin: 'gēge', partOfSpeech: 'n', definition: 'older brother', isProperNoun: false },
  { sourceOrder: 26, word: '两', pinyin: 'liǎng', partOfSpeech: 'nu', definition: 'two; a couple of', isProperNoun: false },
  { sourceOrder: 27, word: '妹妹', pinyin: 'mèimei', partOfSpeech: 'n', definition: 'younger sister', isProperNoun: false },
  { sourceOrder: 28, word: '和', pinyin: 'hé', partOfSpeech: 'conj', definition: 'and', isProperNoun: false },
  { sourceOrder: 29, word: '大姐', pinyin: 'dàjiě', partOfSpeech: 'n', definition: 'eldest sister', isProperNoun: false },
  { sourceOrder: 30, word: '二姐', pinyin: 'èrjiě', partOfSpeech: 'n', definition: 'second oldest sister', isProperNoun: false },
  { sourceOrder: 31, word: '做', pinyin: 'zuò', partOfSpeech: 'v', definition: 'to do', isProperNoun: false },
  { sourceOrder: 32, word: '工作', pinyin: 'gōngzuò', partOfSpeech: 'n/v', definition: 'job; to work', isProperNoun: false },
  { sourceOrder: 33, word: '律师', pinyin: 'lǜshī', partOfSpeech: 'n', definition: 'lawyer', isProperNoun: false },
  { sourceOrder: 34, word: '英文', pinyin: 'Yīngwén', partOfSpeech: 'n', definition: 'English language', isProperNoun: false },
  { sourceOrder: 35, word: '都', pinyin: 'dōu', partOfSpeech: 'adv', definition: 'both; all', isProperNoun: false },
  { sourceOrder: 36, word: '大学生', pinyin: 'dàxuéshēng', partOfSpeech: 'n', definition: 'college student', isProperNoun: false },
  { sourceOrder: 37, word: '医生', pinyin: 'yīshēng', partOfSpeech: 'n', definition: 'doctor; physician', isProperNoun: false },
  { sourceOrder: 38, word: '白英爱', pinyin: "Bái Yīng'ài", partOfSpeech: 'pn', definition: 'personal name', isProperNoun: true },
];

const LESSON_2_DIALOGUES: TutorLine[][] = [
  [
    {
      id: -101,
      chinese: '高文中，那是你的照片吗？',
      pinyin: 'Gāo Wénzhōng, nà shì nǐ de zhàopiàn ma?',
      english: 'Gao Wenzhong, is that picture yours?',
      dialogueNumber: 1,
      sequenceOrder: 1,
      keyVocab: ['那', '的', '照片'],
    },
    {
      id: -102,
      chinese: '是。这是我爸爸，这是我妈妈。',
      pinyin: 'Shì. Zhè shì wǒ bàba, zhè shì wǒ māma.',
      english: 'Yes. This is my dad. This is my mom.',
      dialogueNumber: 1,
      sequenceOrder: 2,
      keyVocab: ['这', '爸爸', '妈妈'],
    },
    {
      id: -103,
      chinese: '这个女孩子是谁？',
      pinyin: 'Zhè ge nǚ háizi shì shéi?',
      english: 'Who is this girl?',
      dialogueNumber: 1,
      sequenceOrder: 3,
      keyVocab: ['个', '女', '孩子', '谁'],
    },
    {
      id: -104,
      chinese: '她是我姐姐。',
      pinyin: 'Tā shì wǒ jiějie.',
      english: 'She is my older sister.',
      dialogueNumber: 1,
      sequenceOrder: 4,
      keyVocab: ['她', '姐姐'],
    },
    {
      id: -105,
      chinese: '这个男孩子是你弟弟吗？',
      pinyin: 'Zhè ge nán háizi shì nǐ dìdi ma?',
      english: 'Is this boy your younger brother?',
      dialogueNumber: 1,
      sequenceOrder: 5,
      keyVocab: ['男', '孩子', '弟弟'],
    },
    {
      id: -106,
      chinese: '不是，他是我大哥的儿子。',
      pinyin: 'Bú shì, tā shì wǒ dàgē de érzi.',
      english: "No, he is my oldest brother's son.",
      dialogueNumber: 1,
      sequenceOrder: 6,
      keyVocab: ['他', '大哥', '的', '儿子'],
    },
    {
      id: -107,
      chinese: '你大哥有女儿吗？',
      pinyin: "Nǐ dàgē yǒu nǚ'ér ma?",
      english: 'Does your oldest brother have any daughters?',
      dialogueNumber: 1,
      sequenceOrder: 7,
      keyVocab: ['大哥', '有', '女儿'],
    },
    {
      id: -108,
      chinese: '他没有女儿。',
      pinyin: "Tā méiyǒu nǚ'ér.",
      english: "He doesn't have any daughters.",
      dialogueNumber: 1,
      sequenceOrder: 8,
      keyVocab: ['他', '没', '有', '女儿'],
    },
  ],
  [
    {
      id: -201,
      chinese: '白英爱，你家有几口人？',
      pinyin: "Bái Yīng'ài, nǐ jiā yǒu jǐ kǒu rén?",
      english: "Bai Ying'ai, how many people are there in your family?",
      dialogueNumber: 2,
      sequenceOrder: 1,
      keyVocab: ['家', '有', '几', '口'],
    },
    {
      id: -202,
      chinese: '我家有六口人。我爸爸、我妈妈、一个哥哥、两个妹妹和我。李友，你家有几口人？',
      pinyin: "Wǒ jiā yǒu liù kǒu rén. Wǒ bàba, wǒ māma, yí ge gēge, liǎng ge mèimei hé wǒ. Lǐ Yǒu, nǐ jiā yǒu jǐ kǒu rén?",
      english: 'There are six people in my family: my dad, my mom, an older brother, two younger sisters and me. Li You, how many people are there in your family?',
      dialogueNumber: 2,
      sequenceOrder: 2,
      keyVocab: ['家', '口', '哥哥', '两', '妹妹', '和'],
    },
    {
      id: -203,
      chinese: '我家有五口人。爸爸、妈妈、大姐、二姐和我。你爸爸妈妈做什么工作？',
      pinyin: 'Wǒ jiā yǒu wǔ kǒu rén. Bàba, māma, dàjiě, èrjiě hé wǒ. Nǐ bàba māma zuò shénme gōngzuò?',
      english: 'There are five people in my family: my dad, my mom, my oldest sister, my second oldest sister, and me. What do your dad and mom do?',
      dialogueNumber: 2,
      sequenceOrder: 3,
      keyVocab: ['大姐', '二姐', '做', '工作'],
    },
    {
      id: -204,
      chinese: '我爸爸是律师，妈妈是英文老师，哥哥、妹妹都是大学生。',
      pinyin: 'Wǒ bàba shì lǜshī, māma shì Yīngwén lǎoshī, gēge, mèimei dōu shì dàxuéshēng.',
      english: 'My dad is a lawyer. My mom is an English teacher. My older brother and younger sisters are all college students.',
      dialogueNumber: 2,
      sequenceOrder: 4,
      keyVocab: ['律师', '英文', '都', '大学生'],
    },
    {
      id: -205,
      chinese: '我妈妈也是老师，我爸爸是医生。',
      pinyin: 'Wǒ māma yě shì lǎoshī, wǒ bàba shì yīshēng.',
      english: 'My mom is also a teacher. My dad is a doctor.',
      dialogueNumber: 2,
      sequenceOrder: 5,
      keyVocab: ['妈妈', '爸爸', '医生'],
    },
  ],
];


export const LESSON_2_TUTOR_CONTENT: TutorContent = {
    lessonNumber: 2,
    title: 'Family',
    chineseTitle: '家庭',
    pinyinTitle: 'Dì èr kè Jiatíng',
    heroCopy: 'Practice the dialogue, notice the patterns, and make the lesson about your own family.',
    sourceNote: 'Source: textbook.pdf Lesson 2',
    detailRoute: '/lessons/2',
    dialogueTitle: 'Dialogue I: Looking at a Family Photo',
    dialogueGuide: 'Work through this dialogue in passes: listen, reveal support, then practice the key lines.',
    vocabNote: 'Curated from the textbook extract and normalized for Lesson 2 order.',
    words: LESSON_2_WORDS,
    dialogues: LESSON_2_DIALOGUES,
    patterns: [
      { title: '有 / 没有', example: '你大哥有女儿吗？ 他没有女儿。', explanation: 'Use 没有 to say someone does not have something.' },
      { title: '几口人', example: '你家有几口人？', explanation: 'Use 口 as the measure word when counting family members.' },
      { title: '都', example: '哥哥、妹妹都是大学生。', explanation: 'Use 都 when the statement applies to both or all people in the group.' },
    ],
    drills: [
      { id: 'you-mei-you', prompt: 'Choose the best answer: 你大哥有女儿吗？', choices: ['他没有女儿。', '他不是女儿。', '他都女儿。'], answer: '他没有女儿。', selected: '', explanation: '有 is negated with 没, so 没有 is the Lesson 2 pattern.' },
      { id: 'measure-kou', prompt: 'Which measure word fits family size?', choices: ['口', '个', '张'], answer: '口', selected: '', explanation: '口 is the idiomatic measure word for number of family members.' },
      { id: 'dou', prompt: 'Complete the idea: 哥哥、妹妹___是大学生。', choices: ['都', '有', '谁'], answer: '都', selected: '', explanation: '都 means both/all and applies to 哥哥、妹妹 here.' },
    ],
    personalPractice: {
      title: 'My Family Builder',
      description: 'Create personal Lesson 2 sentences using the same structures as the dialogue.',
      fields: [
        { key: 'firstNumber', label: 'Family size', inputType: 'number', min: 1, max: 120 },
      ],
      selectionHeading: 'Family members',
      selectionDetailLabel: 'Profession',
      selectionDetailPlaceholder: 'profession',
      generatedLabel: 'Generated practice lines',
      storageKey: 'lessonTutor.familyProfile.v1.lesson2',
      defaultProfile: {
        firstNumber: 4,
        secondNumber: 0,
        firstText: '',
        secondText: '',
        selections: [
          { key: 'father', label: 'Father', chinese: '爸爸', selected: true, detailText: '医生' },
          { key: 'mother', label: 'Mother', chinese: '妈妈', selected: true, detailText: '老师' },
          { key: 'olderBrother', label: 'Older brother', chinese: '哥哥', selected: false, detailText: '大学生' },
          { key: 'olderSister', label: 'Older sister', chinese: '姐姐', selected: false, detailText: '大学生' },
          { key: 'youngerBrother', label: 'Younger brother', chinese: '弟弟', selected: false, detailText: '学生' },
          { key: 'youngerSister', label: 'Younger sister', chinese: '妹妹', selected: false, detailText: '学生' },
        ],
      },
      sentenceTemplates: [
        {
          kind: 'single',
          parts: [
            { kind: 'literal', value: '我家有' },
            { kind: 'profile', key: 'firstNumber' },
            { kind: 'literal', value: '口人。' },
          ],
        },
        {
          kind: 'forEachSelection',
          selected: true,
          parts: [
            { kind: 'literal', value: '我' },
            { kind: 'selection', field: 'chinese' },
            { kind: 'literal', value: '是' },
            { kind: 'selection', field: 'detailText' },
            { kind: 'literal', value: '。' },
          ],
          fallbackParts: [
            { kind: 'literal', value: '我有' },
            { kind: 'selection', field: 'chinese' },
            { kind: 'literal', value: '。' },
          ],
        },
        {
          kind: 'forEachSelection',
          selected: false,
          limit: 2,
          parts: [
            { kind: 'literal', value: '我没有' },
            { kind: 'selection', field: 'chinese' },
            { kind: 'literal', value: '。' },
          ],
        },
      ],
    },
    roleplay: {
      title: 'Family Roleplay',
      description: 'Have a simple conversation about family members and family jobs.',
      scenario: 'The tutor is meeting a beginner learner and asks about the learner family using Lesson 2 vocabulary and patterns.',
      openingLine: {
        chinese: '你家有几口人？',
        pinyin: 'Nǐ jiā yǒu jǐ kǒu rén?',
        english: 'How many people are in your family?',
      },
      targetPatterns: [
        '你家有几口人？',
        '我家有…口人。',
        '你有哥哥/姐姐/弟弟/妹妹吗？',
        '我有… / 我没有…',
        '你爸爸妈妈做什么工作？',
        '我爸爸/妈妈是…',
      ],
      allowedVocabulary: [
        '家',
        '有',
        '没有',
        '几',
        '口',
        '人',
        '爸爸',
        '妈妈',
        '哥哥',
        '姐姐',
        '弟弟',
        '妹妹',
        '儿子',
        '女儿',
        '做',
        '工作',
        '老师',
        '医生',
        '律师',
        '大学生',
        '也',
        '都',
      ],
      conversationGoals: [
        'Ask how many people are in the learner family.',
        'Ask whether the learner has siblings.',
        'Ask what the learner parents do for work.',
        'Keep each tutor turn short and easy for a beginner.',
      ],
    },
  };
